<a href="https://colab.research.google.com/github/YisusBe/ProyectodePrueba/blob/main/Copia_de_Untitled6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''import numpy as np
a = [1, 2, 3, 4, 5, 6]
print (a)

b = np.array(a)
print(b)

print(b.ndim) #para ver que dimencion es

print(len(b)) # esto es para ver su largo
b.shape # para ver cuantos elementos tiene

print(b[-1])


#c = [i for i in b]
#print(c)


for i in range (len(b)):
  print('posicion: ', i ,'valor: ', b[i]) # como recorrer un array


d = np.arange(10)
print(d)
d = d + 1

f = d[:].copy()
f[0] = 100
print(f)
print(d)

e = np.ones(8, dtype = int)
e = e + 1
print(e)

arreglo1 = np.array([2, 8, 5, 9])
arreglo2 = np.array([2, 4, 4, 10]) #estos solo funcionan si ambos tienen la misma cantidad de digitos en este caso 4
suma = arreglo1 + arreglo2 # se puede preguntar si es <, >, == y tambien +, -, /, *
print(suma)


arreglo1 = np.array([2, 3, 5, 9])# esto sirv para usar todos los numeros en casos como: *, -, +, promedio, el valor (min), valor(max), y promedios(mean)
print(arreglo1.sum())'''

In [ ]:
import numpy as np #importar la libreria numpy para poder trabajar
lista = [[3,4,5], [6,7,8]]
matriz = np.array(lista)# matriz con un solo elemento que contiene ambos datos
print(matriz[0,::-1])# se muestra la matriz, y el 0,2 es una cordenada en este caso el 3 seria el 0 y el 5 seria el 2, con el : solo te escribe un lado, y con ::-1 te lo escribe invertido
'''for i in range(2):
  for j in range(3):
    print(matriz[i][j]) #aqui inicia de manera 0,0-0,1-0,2---1,0-1,1-1,2'''


In [ ]:
import numpy as np
matriz = np.diag((3,3,3))
print(matriz)#

[[3 0 0]
 [0 3 0]
 [0 0 3]]


In [ ]:
#clase dia 08/06/2023
def resolverfuncion(x):
  resultado = (2 * x) + 5
  return resultado

def mostrarmenu():
  print("***Menu***")
  print("1. Opcion 1")
  print("2. Opcion 2")
  print("3. Opcion 3")
  print("4. Salir")

def funcionA(nom):
    print(nom)


def funcionB(num1, num2, num3=0, num4=0):#aqui le digo que la funcion b va a tener 4 numeros en ella, y le coloco el = 0 para que si falta entregar un numero lo cuente como un 0
    suma = num1 + num2 + num3 + num4#aqui le digo que va a sumar los 4 numeros que le entregue yo
    return suma

mostrarmenu()
c = resolverecuacion(10)
print(c)
funcionA("Leonel")
d = funcionB(5, 10, 15, 20)#aqui le entrego los valores para que los sume
print(d)

***Menu***
1. Opcion 1
2. Opcion 2
3. Opcion 3
4. Salir
None
Leonel
50


In [ ]:
#para sacar de valor bruto a neto
global numeroBoleta
global IVA
numeroBoleta = 0
IVA = 1.19
def ImprimirBoleta(vNeto):

  vBruto =vNeto * 1.19
  print("El valor total es: ",vBruto)
  numeroBoleta +=1
  return numeroBoleta



c = ImprimirBoleta(1000)
print(c)

d = ImprimirBoleta(2000)
print(d)

El valor total es:  1190.0
1
El valor total es:  2380.0
1


In [ ]:
#ejercicio 1 Repaso Para la Prueba

g